name: eql_cmx_portal_cicd_download_upload_portal_data_pipeline_to_sit_env

on:
  workflow_call :
    secrets:
      build_url:
        description: 'portal_data environment url.'
        required: true      
      build_client_id:
        description: 'The portal_data client id'
        required: true
      build_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      sit_url:
        description: 'portal_data environment url.'
        required: true      
      sit_client_id:
        description: 'The portal_data client id'
        required: true
      sit_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      tenant_id: 
        description: 'The tenant id'
        required: true
        

jobs:
  download-portal-data-from-build-env:
    runs-on:  ubuntu-latest
    environment: build
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: download-paportal
      uses: microsoft/powerplatform-actions/download-paportal@v0
      with:
        environment-url: ${{ secrets.build_url }}
        app-id: ${{ secrets.build_client_id }}
        client-secret: ${{ secrets.build_secrets_id }}
        tenant-id: ${{ secrets.tenant_id }}
        download-path: ${{ secrets.build_url }}
        website-id: 'dd7f978e-c24e-ed11-bba1-000d3a35cd77'
        working-directory: CMX-Pipeline/eql_cmx_portal_cicd_repository_/develop
        

  upload-portal-data-to-sit-env:
    needs: [ download-portal-data-from-build-env ]
    runs-on:  ubuntu-latest
    environment: sit
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true        
    - name: upload-paportal
      uses: microsoft/powerplatform-actions/upload-paportal@v0
      with:
        environment-url: ${{ secrets.sit_url }}
        app-id: ${{ secrets.sit_client_id }}
        client-secret: ${{ secrets.sit_secrets_id }}
        tenant-id: ${{ secrets.tenant_id }}
        download-path: ${{ secrets.sit_url }}
        
