name: eql_cmx_portal_cicd_upload_portal_data_pipeline_to_uat_env

on:
  workflow_call :
    secrets:
      uat_url:
        description: 'portal_data environment url.'
        required: true      
      uat_client_id:
        description: 'The portal_data client id'
        required: true
      uat_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      tenant_id: 
        description: 'The tenant id'
        required: true
        

jobs:
  
        
  upload-portal-data-to-uat-env:
    runs-on:  ubuntu-latest
    environment: uat
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: build-portaldata
    
    - name: upload-paportal
      uses: microsoft/powerplatform-actions/upload-paportal@v0
      with:
        environment-url: ${{ secrets.uat_url }}
        app-id: ${{ secrets.uat_client_id }}
        client-secret: ${{ secrets.uat_secrets_id }}
        tenant-id: ${{ secrets.tenant_id }}
        upload-path: build-portaldata
