name: eql_cmx_portal_cicd_transport_portal_data_pipeline_to_prod_env.yml
# prepare for releasing to prod:

on:
  workflow_call :
    secrets:
      prod_url:
        description: 'portal_data environment url.'
        required: true      
      prod_client_id:
        description: 'The portal_data client id'
        required: true
      prod_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      tenant_id: 
        description: 'The tenant id'
        required: true
        

jobs:
  
        
  upload-portal-data-to-uat-env:
    runs-on:  ubuntu-latest
    environment: prod
    env:
      RUNNER_DEBUG: 1
    steps:

    - name: git config to accept long paths
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git config --system core.longpaths true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: build-portaldata
        path: portaldata
    
    - name: upload-paportal
      uses: microsoft/powerplatform-actions/upload-paportal@v0
      with:
        environment-url: ${{ secrets.prod_url }}
        app-id: ${{ secrets.prod_client_id }}
        client-secret: ${{ secrets.prod_secrets_id }}
        tenant-id: ${{ secrets.tenant_id }}
        upload-path: portaldata  
